### ISSUE TITLE
Split repository?

### ISSUE THREAD

**Issue by AloneCoder** [mailru/top-mail-ru#1]
Maybe it's better to split python/php libraries into separate repos? 
So they will be more relevant in search and structured

**Comment by dedok** [comment]
Hi, sorry for late answer I was on vacation.
Currently we don't see big reasons for separate repositories.
May be in future - but only if those libraries will have packages, better version support etc i.e. more features.

**Comment by AloneCoder** [comment]
Thanks for reply!

**Comment by dedok** [comment]
Thanks for suggesting. I guess we done this issue so I closing it.
